---
jobs:
  final:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Finish cooking
          command: echo "Finished cooking"
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: varnish51-debian-8
          suite: varnish51-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-debian-9
          suite: varnish51-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-centos-6
          suite: varnish51-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-centos-7
          suite: varnish51-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-ubuntu-1604
          suite: varnish51-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-ubuntu-1804
          suite: varnish51-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-debian-8
          suite: varnish52-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-debian-9
          suite: varnish52-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-centos-6
          suite: varnish52-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-centos-7
          suite: varnish52-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-ubuntu-1604
          suite: varnish52-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-ubuntu-1804
          suite: varnish52-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-debian-8
          suite: varnish60-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-debian-9
          suite: varnish60-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-centos-7
          suite: varnish60-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-ubuntu-1604
          suite: varnish60-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-ubuntu-1804
          suite: varnish60-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-debian-8
          suite: varnish61-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-debian-9
          suite: varnish61-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-centos-7
          suite: varnish61-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-ubuntu-1604
          suite: varnish61-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-ubuntu-1804
          suite: varnish61-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-debian-8
          suite: distro-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-debian-9
          suite: distro-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-centos-7
          suite: distro-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-ubuntu-1604
          suite: distro-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-ubuntu-1804
          suite: distro-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-debian-8
          suite: full-stack-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-debian-9
          suite: full-stack-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-centos-7
          suite: full-stack-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-ubuntu-1604
          suite: full-stack-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-ubuntu-1804
          suite: full-stack-ubuntu-1804
          requires: *lint_and_unit
      - final:
          requires:
            - varnish51-debian-8
            - varnish51-debian-9
            - varnish51-centos-6
            - varnish51-centos-7
            - varnish51-ubuntu-1604
            - varnish51-ubuntu-1804
            - varnish52-debian-8
            - varnish52-debian-9
            - varnish52-centos-6
            - varnish52-centos-7
            - varnish52-ubuntu-1604
            - varnish52-ubuntu-1804
            - varnish60-debian-8
            - varnish60-debian-9
            - varnish60-centos-7
            - varnish60-ubuntu-1604
            - varnish60-ubuntu-1804
            - varnish61-debian-8
            - varnish61-debian-9
            - varnish61-centos-7
            - varnish61-ubuntu-1604
            - varnish61-ubuntu-1804
            - distro-debian-8
            - distro-debian-9
            - distro-centos-7
            - distro-ubuntu-1604
            - distro-ubuntu-1804
            - full-stack-debian-8
            - full-stack-debian-9
            - full-stack-centos-7
            - full-stack-ubuntu-1604
            - full-stack-ubuntu-1804
